/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:9a061e0a-6775-4ef0-971c-56fc7339fff8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_kmnO3Cmhu",
    "aws_user_pools_web_client_id": "3vmes08i32hgl82hfuq75640f8",
    "oauth": {}
};


export default awsmobile;
